export const USER_ACTION_TYPES = {
  //Cart
  USERS_CART: 'user/USERS_CART',
  QUANTITY_Cart: 'user/QUANTITY_Cart',
  QUANTITY_DECREASE_Cart:'user/QUANTITY_DECREASE_Cart',
  Add_To_Cart: 'user/ADD_TO_Cart',
  DELETE_CART:'user/DELETE_CART',
  ADD_PRICE:'user/ADD_PRICE',
  REMOVE_PRICE:'user/REMOVE_PRICE',
  //Login
  USER_LOGIN_START: 'user/USER_LOGIN_START',
  USER_LOGIN_SUCCESS: 'user/USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'user/USER_LOGIN_FAILED',
  USER_LOGOUT: 'user/USER_LOGOUT',
};
